version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USER_DEV}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD_DEV}
      POSTGRES_DB: ${DATABASE_NAME_DEV}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - boilerplate-nestjs # change this to your project name
networks:
  boilerplate-nestjs: # change this to your project name
    driver: bridge

# COMMANDS: docker-compose up -d, docker-compose down
