name: Continuous Integration and Deployment (master)

on:
  push:
    branches:
      - master

jobs:
  CI:
    name: Continuos Integration
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Check ESLint
        run: npm run lint
      - name: Make the environment file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_NODE_ENV: ${{secrets.NODE_ENV}}
          envkey_HOST: ${{secrets.HOST}}
          envkey_PORT: ${{secrets.PORT}}
          envkey_JWT_SECRET: ${{secrets.JWT_SECRET}}
          envkey_DATABASE_HOST_PROD: ${{secrets.DATABASE_HOST_PROD}}
          envkey_DATABASE_PORT_PROD: ${{secrets.DATABASE_PORT_PROD}}
          envkey_DATABASE_NAME_PROD: ${{secrets.DATABASE_NAME_PROD}}
          envkey_DATABASE_USER_PROD: ${{secrets.DATABASE_USER_PROD}}
          envkey_DATABASE_PASSWORD_PROD: ${{secrets.DATABASE_PASSWORD_PROD}}
          fail_on_empty: true
      - name: Run handshake
        run: npm run test:handshake
      - name: Run migrations
        run: npm run migration:run
      - name: Run unit tests
        run: npm run test
      - name: Run E2E tests
        run: npm run test:e2e
  CD:
    name: Continuos Deployment
    runs-on: ubuntu-latest
    needs: CI
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      # Write the steps here
